version: "3.9"
services:
  ground-data-service:
    build:
      context: services/ground-data-service/
      network: host
      args:
        - PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
        - PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST}
    ports:
      - "8000:8000"
    volumes:
      - ground-data-storage:/aimlsse/app/data
  satellite-data-service:
    build:
      context: services/satellite-data-service/
      network: host
      args:
        - PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
        - PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST}
    ports:
      - "8010:8010"
    volumes:
      - satellite-data-storage:/aimlsse/app/data
  ground-db:
    image: postgres
    volumes:
      - ground-db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=database

volumes:
  ground-data-storage:
    name: "aimlsse-ground-data-storage"
  satellite-data-storage:
    name: "aimlsse-satellite-data-storage"
  ground-db-storage:
    name: "aimlsse-ground-db-storage"
