services:
  pypi-server:
    image: pypiserver/pypiserver
    volumes:
      - ./packages:/data/packages
    ports:
      - "8060:8080"
  ground-data-service:
    depends_on:
      - pypi-server
      - ground-db
    build: services/ground-data-service/
    ports:
      - "8000:8000"
    volumes:
      - ground-data-storage:/aimlsse/app/data
  satellite-data-service:
    depends_on:
      - pypi-server
    build: services/satellite-data-service/
    ports:
      - "8010:8010"
    volumes:
      - satellite-data-storage:/aimlsse/app/data
  ground-db:
    image: postgres
    volumes:
      - ground-db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=database

volumes:
  ground-data-storage:
    name: "aimlsse-ground-data-storage"
  satellite-data-storage:
    name: "aimlsse-satellite-data-storage"
  ground-db-storage:
    name: "aimlsse-ground-db-storage"
